// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.relationalai.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MetadataInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.relationalai.proto.MetadataInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    java.util.List<com.relationalai.proto.Message.RelationMetadata> 
        getRelationsList();
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    com.relationalai.proto.Message.RelationMetadata getRelations(int index);
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    int getRelationsCount();
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    java.util.List<? extends com.relationalai.proto.Message.RelationMetadataOrBuilder> 
        getRelationsOrBuilderList();
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    com.relationalai.proto.Message.RelationMetadataOrBuilder getRelationsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Describes metadata of a set of relations. 
   * </pre>
   *
   * Protobuf type {@code com.relationalai.proto.MetadataInfo}
   */
  public static final class MetadataInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.relationalai.proto.MetadataInfo)
      MetadataInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MetadataInfo.newBuilder() to construct.
    private MetadataInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetadataInfo() {
      relations_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MetadataInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetadataInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                relations_ = new java.util.ArrayList<com.relationalai.proto.Message.RelationMetadata>();
                mutable_bitField0_ |= 0x00000001;
              }
              relations_.add(
                  input.readMessage(com.relationalai.proto.Message.RelationMetadata.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          relations_ = java.util.Collections.unmodifiableList(relations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.relationalai.proto.Message.internal_static_com_relationalai_proto_MetadataInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.relationalai.proto.Message.internal_static_com_relationalai_proto_MetadataInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.relationalai.proto.Message.MetadataInfo.class, com.relationalai.proto.Message.MetadataInfo.Builder.class);
    }

    public static final int RELATIONS_FIELD_NUMBER = 1;
    private java.util.List<com.relationalai.proto.Message.RelationMetadata> relations_;
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.relationalai.proto.Message.RelationMetadata> getRelationsList() {
      return relations_;
    }
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.relationalai.proto.Message.RelationMetadataOrBuilder> 
        getRelationsOrBuilderList() {
      return relations_;
    }
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    @java.lang.Override
    public int getRelationsCount() {
      return relations_.size();
    }
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    @java.lang.Override
    public com.relationalai.proto.Message.RelationMetadata getRelations(int index) {
      return relations_.get(index);
    }
    /**
     * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
     */
    @java.lang.Override
    public com.relationalai.proto.Message.RelationMetadataOrBuilder getRelationsOrBuilder(
        int index) {
      return relations_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < relations_.size(); i++) {
        output.writeMessage(1, relations_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < relations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, relations_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.relationalai.proto.Message.MetadataInfo)) {
        return super.equals(obj);
      }
      com.relationalai.proto.Message.MetadataInfo other = (com.relationalai.proto.Message.MetadataInfo) obj;

      if (!getRelationsList()
          .equals(other.getRelationsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRelationsCount() > 0) {
        hash = (37 * hash) + RELATIONS_FIELD_NUMBER;
        hash = (53 * hash) + getRelationsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.relationalai.proto.Message.MetadataInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.relationalai.proto.Message.MetadataInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Describes metadata of a set of relations. 
     * </pre>
     *
     * Protobuf type {@code com.relationalai.proto.MetadataInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.relationalai.proto.MetadataInfo)
        com.relationalai.proto.Message.MetadataInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.relationalai.proto.Message.internal_static_com_relationalai_proto_MetadataInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.relationalai.proto.Message.internal_static_com_relationalai_proto_MetadataInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.relationalai.proto.Message.MetadataInfo.class, com.relationalai.proto.Message.MetadataInfo.Builder.class);
      }

      // Construct using com.relationalai.proto.Message.MetadataInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRelationsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (relationsBuilder_ == null) {
          relations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          relationsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.relationalai.proto.Message.internal_static_com_relationalai_proto_MetadataInfo_descriptor;
      }

      @java.lang.Override
      public com.relationalai.proto.Message.MetadataInfo getDefaultInstanceForType() {
        return com.relationalai.proto.Message.MetadataInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.relationalai.proto.Message.MetadataInfo build() {
        com.relationalai.proto.Message.MetadataInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.relationalai.proto.Message.MetadataInfo buildPartial() {
        com.relationalai.proto.Message.MetadataInfo result = new com.relationalai.proto.Message.MetadataInfo(this);
        int from_bitField0_ = bitField0_;
        if (relationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            relations_ = java.util.Collections.unmodifiableList(relations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.relations_ = relations_;
        } else {
          result.relations_ = relationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.relationalai.proto.Message.MetadataInfo) {
          return mergeFrom((com.relationalai.proto.Message.MetadataInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.relationalai.proto.Message.MetadataInfo other) {
        if (other == com.relationalai.proto.Message.MetadataInfo.getDefaultInstance()) return this;
        if (relationsBuilder_ == null) {
          if (!other.relations_.isEmpty()) {
            if (relations_.isEmpty()) {
              relations_ = other.relations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRelationsIsMutable();
              relations_.addAll(other.relations_);
            }
            onChanged();
          }
        } else {
          if (!other.relations_.isEmpty()) {
            if (relationsBuilder_.isEmpty()) {
              relationsBuilder_.dispose();
              relationsBuilder_ = null;
              relations_ = other.relations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              relationsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRelationsFieldBuilder() : null;
            } else {
              relationsBuilder_.addAllMessages(other.relations_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.relationalai.proto.Message.MetadataInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.relationalai.proto.Message.MetadataInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.relationalai.proto.Message.RelationMetadata> relations_ =
        java.util.Collections.emptyList();
      private void ensureRelationsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          relations_ = new java.util.ArrayList<com.relationalai.proto.Message.RelationMetadata>(relations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.relationalai.proto.Message.RelationMetadata, com.relationalai.proto.Message.RelationMetadata.Builder, com.relationalai.proto.Message.RelationMetadataOrBuilder> relationsBuilder_;

      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public java.util.List<com.relationalai.proto.Message.RelationMetadata> getRelationsList() {
        if (relationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(relations_);
        } else {
          return relationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public int getRelationsCount() {
        if (relationsBuilder_ == null) {
          return relations_.size();
        } else {
          return relationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public com.relationalai.proto.Message.RelationMetadata getRelations(int index) {
        if (relationsBuilder_ == null) {
          return relations_.get(index);
        } else {
          return relationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder setRelations(
          int index, com.relationalai.proto.Message.RelationMetadata value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.set(index, value);
          onChanged();
        } else {
          relationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder setRelations(
          int index, com.relationalai.proto.Message.RelationMetadata.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.set(index, builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder addRelations(com.relationalai.proto.Message.RelationMetadata value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.add(value);
          onChanged();
        } else {
          relationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder addRelations(
          int index, com.relationalai.proto.Message.RelationMetadata value) {
        if (relationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRelationsIsMutable();
          relations_.add(index, value);
          onChanged();
        } else {
          relationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder addRelations(
          com.relationalai.proto.Message.RelationMetadata.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.add(builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder addRelations(
          int index, com.relationalai.proto.Message.RelationMetadata.Builder builderForValue) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.add(index, builderForValue.build());
          onChanged();
        } else {
          relationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder addAllRelations(
          java.lang.Iterable<? extends com.relationalai.proto.Message.RelationMetadata> values) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, relations_);
          onChanged();
        } else {
          relationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder clearRelations() {
        if (relationsBuilder_ == null) {
          relations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          relationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public Builder removeRelations(int index) {
        if (relationsBuilder_ == null) {
          ensureRelationsIsMutable();
          relations_.remove(index);
          onChanged();
        } else {
          relationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public com.relationalai.proto.Message.RelationMetadata.Builder getRelationsBuilder(
          int index) {
        return getRelationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public com.relationalai.proto.Message.RelationMetadataOrBuilder getRelationsOrBuilder(
          int index) {
        if (relationsBuilder_ == null) {
          return relations_.get(index);  } else {
          return relationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public java.util.List<? extends com.relationalai.proto.Message.RelationMetadataOrBuilder> 
           getRelationsOrBuilderList() {
        if (relationsBuilder_ != null) {
          return relationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(relations_);
        }
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public com.relationalai.proto.Message.RelationMetadata.Builder addRelationsBuilder() {
        return getRelationsFieldBuilder().addBuilder(
            com.relationalai.proto.Message.RelationMetadata.getDefaultInstance());
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public com.relationalai.proto.Message.RelationMetadata.Builder addRelationsBuilder(
          int index) {
        return getRelationsFieldBuilder().addBuilder(
            index, com.relationalai.proto.Message.RelationMetadata.getDefaultInstance());
      }
      /**
       * <code>repeated .com.relationalai.proto.RelationMetadata relations = 1;</code>
       */
      public java.util.List<com.relationalai.proto.Message.RelationMetadata.Builder> 
           getRelationsBuilderList() {
        return getRelationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.relationalai.proto.Message.RelationMetadata, com.relationalai.proto.Message.RelationMetadata.Builder, com.relationalai.proto.Message.RelationMetadataOrBuilder> 
          getRelationsFieldBuilder() {
        if (relationsBuilder_ == null) {
          relationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.relationalai.proto.Message.RelationMetadata, com.relationalai.proto.Message.RelationMetadata.Builder, com.relationalai.proto.Message.RelationMetadataOrBuilder>(
                  relations_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          relations_ = null;
        }
        return relationsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.relationalai.proto.MetadataInfo)
    }

    // @@protoc_insertion_point(class_scope:com.relationalai.proto.MetadataInfo)
    private static final com.relationalai.proto.Message.MetadataInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.relationalai.proto.Message.MetadataInfo();
    }

    public static com.relationalai.proto.Message.MetadataInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MetadataInfo>
        PARSER = new com.google.protobuf.AbstractParser<MetadataInfo>() {
      @java.lang.Override
      public MetadataInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MetadataInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetadataInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetadataInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.relationalai.proto.Message.MetadataInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RelationMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.relationalai.proto.RelationMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Type signature of this relation.
     * </pre>
     *
     * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
     * @return Whether the relationId field is set.
     */
    boolean hasRelationId();
    /**
     * <pre>
     * Type signature of this relation.
     * </pre>
     *
     * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
     * @return The relationId.
     */
    com.relationalai.proto.Schema.RelationId getRelationId();
    /**
     * <pre>
     * Type signature of this relation.
     * </pre>
     *
     * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
     */
    com.relationalai.proto.Schema.RelationIdOrBuilder getRelationIdOrBuilder();

    /**
     * <pre>
     * Identifier for the corresponding data file.
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The fileName.
     */
    java.lang.String getFileName();
    /**
     * <pre>
     * Identifier for the corresponding data file.
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The bytes for fileName.
     */
    com.google.protobuf.ByteString
        getFileNameBytes();
  }
  /**
   * <pre>
   * Describes metadata of a single relation.
   * </pre>
   *
   * Protobuf type {@code com.relationalai.proto.RelationMetadata}
   */
  public static final class RelationMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.relationalai.proto.RelationMetadata)
      RelationMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RelationMetadata.newBuilder() to construct.
    private RelationMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RelationMetadata() {
      fileName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RelationMetadata();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RelationMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.relationalai.proto.Schema.RelationId.Builder subBuilder = null;
              if (relationId_ != null) {
                subBuilder = relationId_.toBuilder();
              }
              relationId_ = input.readMessage(com.relationalai.proto.Schema.RelationId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(relationId_);
                relationId_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              fileName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.relationalai.proto.Message.internal_static_com_relationalai_proto_RelationMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.relationalai.proto.Message.internal_static_com_relationalai_proto_RelationMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.relationalai.proto.Message.RelationMetadata.class, com.relationalai.proto.Message.RelationMetadata.Builder.class);
    }

    public static final int RELATION_ID_FIELD_NUMBER = 1;
    private com.relationalai.proto.Schema.RelationId relationId_;
    /**
     * <pre>
     * Type signature of this relation.
     * </pre>
     *
     * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
     * @return Whether the relationId field is set.
     */
    @java.lang.Override
    public boolean hasRelationId() {
      return relationId_ != null;
    }
    /**
     * <pre>
     * Type signature of this relation.
     * </pre>
     *
     * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
     * @return The relationId.
     */
    @java.lang.Override
    public com.relationalai.proto.Schema.RelationId getRelationId() {
      return relationId_ == null ? com.relationalai.proto.Schema.RelationId.getDefaultInstance() : relationId_;
    }
    /**
     * <pre>
     * Type signature of this relation.
     * </pre>
     *
     * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
     */
    @java.lang.Override
    public com.relationalai.proto.Schema.RelationIdOrBuilder getRelationIdOrBuilder() {
      return getRelationId();
    }

    public static final int FILE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object fileName_;
    /**
     * <pre>
     * Identifier for the corresponding data file.
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The fileName.
     */
    @java.lang.Override
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Identifier for the corresponding data file.
     * </pre>
     *
     * <code>string file_name = 2;</code>
     * @return The bytes for fileName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (relationId_ != null) {
        output.writeMessage(1, getRelationId());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fileName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (relationId_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRelationId());
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fileName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fileName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.relationalai.proto.Message.RelationMetadata)) {
        return super.equals(obj);
      }
      com.relationalai.proto.Message.RelationMetadata other = (com.relationalai.proto.Message.RelationMetadata) obj;

      if (hasRelationId() != other.hasRelationId()) return false;
      if (hasRelationId()) {
        if (!getRelationId()
            .equals(other.getRelationId())) return false;
      }
      if (!getFileName()
          .equals(other.getFileName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRelationId()) {
        hash = (37 * hash) + RELATION_ID_FIELD_NUMBER;
        hash = (53 * hash) + getRelationId().hashCode();
      }
      hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFileName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.relationalai.proto.Message.RelationMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.relationalai.proto.Message.RelationMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Describes metadata of a single relation.
     * </pre>
     *
     * Protobuf type {@code com.relationalai.proto.RelationMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.relationalai.proto.RelationMetadata)
        com.relationalai.proto.Message.RelationMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.relationalai.proto.Message.internal_static_com_relationalai_proto_RelationMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.relationalai.proto.Message.internal_static_com_relationalai_proto_RelationMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.relationalai.proto.Message.RelationMetadata.class, com.relationalai.proto.Message.RelationMetadata.Builder.class);
      }

      // Construct using com.relationalai.proto.Message.RelationMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (relationIdBuilder_ == null) {
          relationId_ = null;
        } else {
          relationId_ = null;
          relationIdBuilder_ = null;
        }
        fileName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.relationalai.proto.Message.internal_static_com_relationalai_proto_RelationMetadata_descriptor;
      }

      @java.lang.Override
      public com.relationalai.proto.Message.RelationMetadata getDefaultInstanceForType() {
        return com.relationalai.proto.Message.RelationMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public com.relationalai.proto.Message.RelationMetadata build() {
        com.relationalai.proto.Message.RelationMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.relationalai.proto.Message.RelationMetadata buildPartial() {
        com.relationalai.proto.Message.RelationMetadata result = new com.relationalai.proto.Message.RelationMetadata(this);
        if (relationIdBuilder_ == null) {
          result.relationId_ = relationId_;
        } else {
          result.relationId_ = relationIdBuilder_.build();
        }
        result.fileName_ = fileName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.relationalai.proto.Message.RelationMetadata) {
          return mergeFrom((com.relationalai.proto.Message.RelationMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.relationalai.proto.Message.RelationMetadata other) {
        if (other == com.relationalai.proto.Message.RelationMetadata.getDefaultInstance()) return this;
        if (other.hasRelationId()) {
          mergeRelationId(other.getRelationId());
        }
        if (!other.getFileName().isEmpty()) {
          fileName_ = other.fileName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.relationalai.proto.Message.RelationMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.relationalai.proto.Message.RelationMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.relationalai.proto.Schema.RelationId relationId_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.relationalai.proto.Schema.RelationId, com.relationalai.proto.Schema.RelationId.Builder, com.relationalai.proto.Schema.RelationIdOrBuilder> relationIdBuilder_;
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       * @return Whether the relationId field is set.
       */
      public boolean hasRelationId() {
        return relationIdBuilder_ != null || relationId_ != null;
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       * @return The relationId.
       */
      public com.relationalai.proto.Schema.RelationId getRelationId() {
        if (relationIdBuilder_ == null) {
          return relationId_ == null ? com.relationalai.proto.Schema.RelationId.getDefaultInstance() : relationId_;
        } else {
          return relationIdBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      public Builder setRelationId(com.relationalai.proto.Schema.RelationId value) {
        if (relationIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          relationId_ = value;
          onChanged();
        } else {
          relationIdBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      public Builder setRelationId(
          com.relationalai.proto.Schema.RelationId.Builder builderForValue) {
        if (relationIdBuilder_ == null) {
          relationId_ = builderForValue.build();
          onChanged();
        } else {
          relationIdBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      public Builder mergeRelationId(com.relationalai.proto.Schema.RelationId value) {
        if (relationIdBuilder_ == null) {
          if (relationId_ != null) {
            relationId_ =
              com.relationalai.proto.Schema.RelationId.newBuilder(relationId_).mergeFrom(value).buildPartial();
          } else {
            relationId_ = value;
          }
          onChanged();
        } else {
          relationIdBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      public Builder clearRelationId() {
        if (relationIdBuilder_ == null) {
          relationId_ = null;
          onChanged();
        } else {
          relationId_ = null;
          relationIdBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      public com.relationalai.proto.Schema.RelationId.Builder getRelationIdBuilder() {
        
        onChanged();
        return getRelationIdFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      public com.relationalai.proto.Schema.RelationIdOrBuilder getRelationIdOrBuilder() {
        if (relationIdBuilder_ != null) {
          return relationIdBuilder_.getMessageOrBuilder();
        } else {
          return relationId_ == null ?
              com.relationalai.proto.Schema.RelationId.getDefaultInstance() : relationId_;
        }
      }
      /**
       * <pre>
       * Type signature of this relation.
       * </pre>
       *
       * <code>.com.relationalai.proto.RelationId relation_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.relationalai.proto.Schema.RelationId, com.relationalai.proto.Schema.RelationId.Builder, com.relationalai.proto.Schema.RelationIdOrBuilder> 
          getRelationIdFieldBuilder() {
        if (relationIdBuilder_ == null) {
          relationIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.relationalai.proto.Schema.RelationId, com.relationalai.proto.Schema.RelationId.Builder, com.relationalai.proto.Schema.RelationIdOrBuilder>(
                  getRelationId(),
                  getParentForChildren(),
                  isClean());
          relationId_ = null;
        }
        return relationIdBuilder_;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <pre>
       * Identifier for the corresponding data file.
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @return The fileName.
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Identifier for the corresponding data file.
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @return The bytes for fileName.
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Identifier for the corresponding data file.
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @param value The fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifier for the corresponding data file.
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFileName() {
        
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Identifier for the corresponding data file.
       * </pre>
       *
       * <code>string file_name = 2;</code>
       * @param value The bytes for fileName to set.
       * @return This builder for chaining.
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.relationalai.proto.RelationMetadata)
    }

    // @@protoc_insertion_point(class_scope:com.relationalai.proto.RelationMetadata)
    private static final com.relationalai.proto.Message.RelationMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.relationalai.proto.Message.RelationMetadata();
    }

    public static com.relationalai.proto.Message.RelationMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RelationMetadata>
        PARSER = new com.google.protobuf.AbstractParser<RelationMetadata>() {
      @java.lang.Override
      public RelationMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RelationMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RelationMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RelationMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.relationalai.proto.Message.RelationMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_relationalai_proto_MetadataInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_relationalai_proto_MetadataInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_relationalai_proto_RelationMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_relationalai_proto_RelationMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\026com.relationalai.proto\032" +
      "\014schema.proto\"K\n\014MetadataInfo\022;\n\trelatio" +
      "ns\030\001 \003(\0132(.com.relationalai.proto.Relati" +
      "onMetadata\"^\n\020RelationMetadata\0227\n\013relati" +
      "on_id\030\001 \001(\0132\".com.relationalai.proto.Rel" +
      "ationId\022\021\n\tfile_name\030\002 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.relationalai.proto.Schema.getDescriptor(),
        });
    internal_static_com_relationalai_proto_MetadataInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_relationalai_proto_MetadataInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_relationalai_proto_MetadataInfo_descriptor,
        new java.lang.String[] { "Relations", });
    internal_static_com_relationalai_proto_RelationMetadata_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_relationalai_proto_RelationMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_relationalai_proto_RelationMetadata_descriptor,
        new java.lang.String[] { "RelationId", "FileName", });
    com.relationalai.proto.Schema.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
