#!/bin/bash

#
# Script for running a single example java file.
#
# Usage:
#
#     ./run <sample-name>
#
# Example:
#
#     ./run ListDatabases
#

set -ex

javac -cp "./examples:./target/*:./target/dependency/*" -d "./target/classes" examples/$1.java
java -cp "./target/classes:./target/*:./target/dependency/*" $1 $2 $3 $4 $5 $6 $7 $8 $9
