name: build/test

on:
  push:
  schedule:
    - cron: '30 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11, 17, 18 ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          client_credentials_url: ${{ secrets.CLIENT_CREDENTIALS_URL }}
