name: SDK Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_CREDENTIALS_URL: ${{ secrets.CLIENT_CREDENTIALS_URL }}
        run: |
          mvn clean package
          mvn test -Dtest="LoadJsonTest"
          mvn test -Dtest="LoadCsvTest"
          mvn test -Dtest="ModelsTest"
          mvn test -Dtest="UserTest"
          mvn test -Dtest="ExecuteTest"
          mvn test -Dtest="OAuthClientTest"
          mvn test -Dtest="DatabaseTest"
          mvn test -Dtest="EngineTest"
